fixed unknown_host
sonyxperiadev/pygerrit pull request #40
Opened 2018-12-27 06:56 UTC by rikiesxiao

fixed the below [issue](https://github.com/onyxfish/relay/issues/11). 
paramiko.SSHException: Server '[10.10.40.10]:8888' not found in known_hosts

2019-01-21 01:07 UTC, dpursehouse commented on pygerrit/ssh.py
> +import paramiko
It would be better to update line 32 to also import `AutoAddPolicy`

2019-01-21 01:07 UTC, dpursehouse commented on pygerrit/ssh.py
> +            self.set_missing_host_key_policy(paramiko.AutoAddPolicy())
The `paramiko.` prefix can be removed if `AutoAddPolicy` is imported as mentioned above.

2019-01-21 01:08 UTC, dpursehouse requested changes
See inline comments.

2019-03-27 17:29 UTC, copland commented
@rikiesxiao Are you still interested in making these changes? I hit this issue as well and would be happy to help get this over the finish line.

2019-04-15 04:56 UTC, dpursehouse commented
Superseded by #41

2019-04-15 04:56 UTC, closed without merging